name: gridwalker
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.10+10

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  maplibre_gl: ^0.25.0
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.5
  flutter_p2p_connection: ^3.0.3
  geolocator: ^14.0.2
  github: ^9.25.0
  dio: ^5.9.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  latlong2: ^0.9.1
  http: ^1.6.0
  shared_preferences: ^2.5.3
  file_picker: ^10.3.10
  share_plus: ^12.0.1
  url_launcher: ^6.3.2
  upgrader: ^11.4.0
  image_picker: ^1.1.2
  encrypt: ^5.0.3
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.4
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  isar_generator: 3.1.0+1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "gridwalker_sar_icon.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - gridwalker_sar_icon.jpg
