name: gridwalker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  maplibre_gl: ^0.25.0
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.5
  flutter_p2p_connection: ^3.0.3
  geolocator: ^14.0.2
  github: ^9.25.0
  dio: ^5.9.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  isar_generator: 3.1.0+1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
